version: "3.9"

services:
  bot:
    image: ysaron/hdhapibot:latest
    command: python bot.py
    restart: always
    env_file:
      - .env
    depends_on:
      - redis
  redis:
    image: redis:7
    command: redis-server --requirepass ${REDIS_HOST_PASSWORD}
    expose:
      - '6379'
    volumes:
      - redis_hdh:/data

volumes:
  redis_hdh:
